[general]
GEMINI_API_KEY = "AIzaSyDNNDqZtJJp7gVmUf7i6cZaGWbqhmq2v84"
QDRANT_URL = "https://014ab865-1a9a-4387-8672-182fbfbb2dba.us-east4-0.gcp.cloud.qdrant.io:6333"
QDRANT_API_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3MiOiJtIn0.L9k9OYrFXW0loBo8w1LXORHr5oG8cLbjN4Fg3w2dWOw"
GROQ_API_KEY = ""  # Optional, leave empty if not using

[rag variables]

LLM_PROVIDER=gemini
MODEL=gemini-2.5-flash-lite

ENABLE_CITATIONS=true

# Other settings
TEMPERATURE=0.3
TOP_P=0.5
MAX_TOKENS=2048
TIMEOUT=600
MAX_RETRIES=2
CHUNK_SIZE=768
CHUNK_OVERLAP=128

RETRIEVAL_K=5

SEMANTIC_WEIGHT=0.7
KEYWORD_WEIGHT=0.3

EXPANSION_DOCS=3

CHAT_MEMORY_WINDOW=5
TOPIC_CHANGE_WINDOW=3
COLLECTION_NAME=ancient_history

EVAL_LLM_PROVIDER=gemini
GEMINI_MODEL=gemini-2.5-flash-lite
