[general]
GEMINI_API_KEY = "AIzaSyDNNDqZtJJp7gVmUf7i6cZaGWbqhmq2v84"
QDRANT_URL = "https://014ab865-1a9a-4387-8672-182fbfbb2dba.us-east4-0.gcp.cloud.qdrant.io:6333"
QDRANT_API_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3MiOiJtIn0.L9k9OYrFXW0loBo8w1LXORHr5oG8cLbjN4Fg3w2dWOw"
GROQ_API_KEY = ""  # Optional, leave empty if not using
